builders:
  mek_adapters:
    import: package:mek_json_adapter/builder.dart
    builder_factories: [ 'buildAdapters' ]
    build_extensions: { "lib/{{}}.dart": [ "lib/generated/{{}}.adapters.g.dart" ] }
    auto_apply: root_package # dependents all_packages
    build_to: source
    runs_before: ['mek_bundle_adapters', 'mek_bundle_adapters_v2']
  mek_bundle_adapters:
    import: package:mek_json_adapter/builder.dart
    builder_factories: [ 'buildBundleAdapters' ]
    build_extensions: { "$lib$": [ "adapters.g.dart" ] }
    auto_apply: root_package # dependents all_packages
    build_to: source
    required_inputs: [ '.adapters.g.dart' ]
  mek_bundle_adapters_v2:
    import: package:mek_json_adapter/builder.dart
    builder_factories: [ 'buildBundleAdaptersV2' ]
    build_extensions: { "{{}}.dart": [ "{{}}adapters_v2.g.dart" ] }
    auto_apply: root_package # dependents all_packages
    build_to: source
    required_inputs: [ '.adapters.g.dart' ]



