builders:
  mek_adapters:
    import: package:mek_json_adapter/builder.dart
    builder_factories: [ 'buildAdapters' ]
    build_extensions: { "lib/{{}}.dart": [ "lib/generated/{{}}.adapters.dart" ] }
    auto_apply: root_package # dependents all_packages
    build_to: source
    runs_before: [ 'mek_bundle_adapters' ]
  mek_bundle_adapters:
    import: package:mek_json_adapter/builder.dart
    builder_factories: [ 'buildBundleAdapters' ]
    build_extensions: { "lib/{{}}_adapters.dart": [ "lib/{{}}_adapters.bundle.dart" ] }
    auto_apply: root_package # dependents all_packages
    build_to: source
    required_inputs: [ '.adapters.dart' ]



