name: mek_json_adapter
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  mek_adaptable: ^0.0.0

  collection: ^1.16.0
  diacritic: ^0.1.3
  meta: ^1.7.0
  pure_extensions: ^4.2.0
  tuple: ^2.0.0

  path: ^1.8.1
  glob: ^2.0.2
  file: ^6.1.2

  source_helper: '>=1.3.0'
  code_builder: '>=4.1.0'

  analyzer: '>=2.6.0'
  build: '>=1.0.0'
  source_gen: '>=0.9.0'
  dart_style: '>=2.0.0'

dependency_overrides:
  mek_adaptable:
    path: ../mek_adaptable

dev_dependencies:
  lints: ^2.0.0

  test: ^1.21.1

  build_runner: ^2.1.11
